name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
          uses: golangci/golangci-lint-action@v2
          with:
            # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
            version: v1.29
            # Optional: golangci-lint command line arguments.
            # args: --issues-exit-code=0
            # Optional: if set to true then the action will use pre-installed Go
            # skip-go-installation: true

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Unit tests.
        run: go test -v .